language: python
python:
  - '2.7'
install: pip install -r requirements.txt --use-mirrors
script: make test
before_script:
  - psql -c 'create database zerocycle;' -U postgres
notifications:
  email:
    recipients:
      - benjamin@bengfort.com
    on_success: change
    on_failure: always
